-- MySQL schema for NutriLanka (import into XAMPP phpMyAdmin)
CREATE DATABASE IF NOT EXISTS nutrilanka CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nutrilanka;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150),
  email VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255),
  provider VARCHAR(50) NOT NULL DEFAULT 'local',
  providerId VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
